-- Enable extensions needed for scheduled re-embedding
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

-- Clear stale OpenAI embeddings; new ones will be regenerated by the
-- scheduled re-embed job using Lovable AI (gemini-embedding-001).
TRUNCATE TABLE public.library_embeddings;